import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "@/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HotGlobal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let toast;
  if (typeof window !== "undefined") {
    toast = require("react-toastify").toast;
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="container">
            <div className="wrapper">
              <Navbar></Navbar>
              {children}
              <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                transition={toast ? toast.TRANSITION.BOUNCE : undefined}
                theme="dark"
              />
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
